# Site configuration

title: We Love Speed
seo_title: We Love Speed
description: "L’événement français des mordus de web performance !"
description_en: "The French event for web performance enthusiasts"
logo: /assets/images/twittercard.png
url: https://www.welovespeed.com
domain: 'welovespeed.com'
mail: contact@welovespeed.com
main_color: cd2f2b
social:
  twitter:
    url: https://twitter.com/_welovespeed
    nick: "@_welovespeed"
  mastodon:
    url: https://piaille.fr/@welovespeed
    nick: "@welovespeed@piaille.fr"
repository: welovespeed/welovespeed.com
baseurl: ""
destination: _site/
locale: fr_FR
logo: https://welovespeed.com/assets/images/social/logo.jpg
matomo: false
lazyload:
  placeholder: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="


current_edition: 2024
cfp_open: false
sponsoring:
  show: true
  up_to_date: false
  fr_FR:
    url: '/assets/docs/2023/sponsoring_fr.pdf'
    size: '495 Ko'
  en_US:
    url: '/assets/docs/2023/sponsoring_en.pdf'
    size: '675KB'
tickets:
  selling: true # pensez à regénérer les bannières de conférence avant mise en prod
  weezevent: true
  coupons-only: false
  waiting-list: false
  price: "200"
  price_currency: "EUR"
nlOnTop: true
infos:
  display: true
  diversity:
    active: false
    soldout: false
  interventions: false
  schedule: false # pensez à regénérer les bannières de conférence avant mise en prod

# Compression du code HTML en production
compress_html:
  ignore:
    envs:
      - 'development'

## SEO

robots: index,follow

# Services configuration

weezevent:
    mini-site-url: https://my.weezevent.com/we-love-speed-2024
    base_url: https://widget.weezevent.com/ticket/E1115910/?code=55656
    dataId: 1115910

appyuser: 7135870c152d8c2f73b35ab582eb7e5a

newsletter:
  url: "https://welovespeed.us18.list-manage.com/subscribe/post?u=871757160e8496642288193e3&amp;id=1695ce944b"
  honeypot: "b_871757160e8496642288193e3_1695ce944b"

# Jekyll configuration

timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

cloudinary:
  cloud_name: we-love-speed
  origin_url: "https://welovespeed.netlify.com"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
    gold_sponsors:
      min_width: 60
      max_width: 1760
      fallback_max_width: 880
      steps: 3
      sizes: "100px"
    avatar:
      min_width: 115 # for some reason, cloudinary refuses to create 110px images ¯\_(ツ)_/¯
      max_width: 220
      fallback_max_width: 220
      steps: 2
      sizes: "110px"
    thumbnail:
      min_width: 33
      max_width: 66
      fallback_max_width: 33
      steps: 2
      sizes: "33px"

permalink: "/blog/:year-:month-:day-:slug/"

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  talks:
    output: true
    order: date asc
    sitemap: false

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/en"
      locale: en_US
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "_talks/fr"
      type: "talks"
    values:
      permalink: /:year/talks/:slug/
      layout: talk
      locale: fr_FR
  -
    scope:
      path: "_talks/en"
      type: "talks"
    values:
      permalink: /en/:year/talks/:slug/
      baseurl: "/en"
      locale: en_US
      layout: talk
  -
    scope:
      path: "pages/fr/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/en/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/fr/2019"
    values:
      year: 2019
  -
    scope:
      path: "pages/en/2019"
    values:
      year: 2019
  -
    scope:
      path: "pages/en/2020"
    values:
      year: 2020
  -
    scope:
      path: "pages/fr/2020"
    values:
      year: 2020
  -
    scope:
      path: "pages/en/2021"
    values:
      year: 2021
  -
    scope:
      path: "pages/fr/2021"
    values:
      year: 2021
  -
    scope:
      path: "pages/en/2023"
    values:
      year: 2023
  -
    scope:
      path: "pages/fr/2023"
    values:
      year: 2023
  -
    scope:
      path: "pages/en/2024"
    values:
      year: 2024
  -
    scope:
      path: "pages/fr/2024"
    values:
      year: 2024
  -
    scope:
      path: "_talks/en/2018"
    values:
      year: 2018
      permalink: /en/2018/talks/:slug/
      seo_image: /assets/images/social/en/talks/2018/:slug.jpg
  -
    scope:
      path: "_talks/en/2019"
    values:
      year: 2019
      permalink: /en/2019/talks/:slug/
      seo_image: /assets/images/social/en/talks/2019/:slug.jpg
  -
    scope:
      path: "_talks/en/2020"
    values:
      year: 2020
      permalink: /en/2020/talks/:slug/
      seo_image: /assets/images/social/en/talks/2020/:slug.jpg
  -
    scope:
      path: "_talks/en/2021"
    values:
      year: 2021
      permalink: /en/2021/talks/:slug/
      seo_image: /assets/images/social/en/talks/2021/:slug.jpg
  -
    scope:
      path: "_talks/en/2023"
    values:
      year: 2023
      permalink: /en/2023/talks/:slug/
      seo_image: /assets/images/social/en/talks/2023/:slug.jpg
  -
    scope:
      path: "_talks/en/2024"
    values:
      year: 2024
      permalink: /en/2024/talks/:slug/
      seo_image: /assets/images/social/en/talks/2024/:slug.jpg
  -
    scope:
      path: "_talks/fr/2018"
    values:
      year: 2018
      permalink: /2018/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2018/:slug.jpg
  -
    scope:
      path: "_talks/fr/2019"
    values:
      year: 2019
      permalink: /2019/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2019/:slug.jpg
  -
    scope:
      path: "_talks/fr/2020"
    values:
      year: 2020
      permalink: /2020/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2020/:slug.jpg
  -
    scope:
      path: "_talks/fr/2021"
    values:
      year: 2021
      permalink: /2021/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2021/:slug.jpg
  -
    scope:
      path: "_talks/fr/2023"
    values:
      year: 2023
      permalink: /2023/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2023/:slug.jpg
  -
    scope:
      path: "_talks/fr/2024"
    values:
      year: 2024
      permalink: /2024/talks/:slug/
      seo_image: /assets/images/social/fr/talks/2024/:slug.jpg
  -
    scope:
      path: "admin"
      type: pages
    values:
      layout: admin
microtypo:
  median: true

include:
  - _headers
  - _redirects

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script
  - "Rakefile"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
