# Site configuration

title: We Love Speed
seo_title: We Love Speed
description: "L’événement français des mordus de web performance !"
description_en: "The French event for web performance enthusiasts"
logo: /assets/images/twittercard.png
url: https://www.welovespeed.com
domain: 'welovespeed.com'
mail: contact@welovespeed.com
main_color: cd2f2b
social:
  twitter:
    url: https://twitter.com/_welovespeed
    nick: "@_welovespeed"
  mastodon:
    url: https://piaille.fr/@welovespeed
    nick: "@welovespeed@piaille.fr"
repository: welovespeed/welovespeed.com
baseurl: ""
destination: _site/
locale: fr_FR
logo: https://welovespeed.com/assets/images/social/logo.jpg
matomo: false
lazyload:
  placeholder: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="


current_edition: 2023
cfp_open: false
sponsoring:
  show: false
  fr_FR:
    url: '/assets/docs/2023/sponsoring_fr.pdf'
    size: '495 Ko'
  en_US:
    url: '/assets/docs/2023/sponsoring_en.pdf'
    size: '675KB'
tickets:
  selling: false
  weezevent: true
  coupons-only: false
  waiting-list: false
  price: "250"
  price_currency: "EUR"
nlOnTop: false
infos:
  display: true
  diversity:
    active: false
    soldout: false

# Compression du code HTML en production
compress_html:
  ignore:
    envs:
      - 'development'

## SEO

robots: index,follow

# Services configuration

weezevent:
    mini-site-url: https://my.weezevent.com/we-love-speed-2023
    base_url: https://widget.weezevent.com/ticket/E931463/?code=24576
    dataId: 931463

appyuser: 7135870c152d8c2f73b35ab582eb7e5a

newsletter:
  url: "https://welovespeed.us18.list-manage.com/subscribe/post?u=871757160e8496642288193e3&amp;id=1695ce944b"
  honeypot: "b_871757160e8496642288193e3_1695ce944b"

# Jekyll configuration

timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

cloudinary:
  cloud_name: we-love-speed
  origin_url: "https://welovespeed.netlify.com"
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
    gold_sponsors:
      min_width: 60
      max_width: 1760
      fallback_max_width: 880
      steps: 3
      sizes: "100px"
    avatar:
      min_width: 60
      max_width: 110
      fallback_max_width: 220
      steps: 2
      sizes: "110px"

permalink: "/blog/:year-:month-:day-:slug/"

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  talks:
    output: false
    order: date asc
    permalink: /talks/:path/
    sitemap: false

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/en"
      locale: en_US
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "pages/fr/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/en/2018"
    values:
      year: 2018
  -
    scope:
      path: "pages/fr/2019"
    values:
      year: 2019
  -
    scope:
      path: "pages/en/2019"
    values:
      year: 2019
  -
    scope:
      path: "pages/en/2020"
    values:
      year: 2020
  -
    scope:
      path: "pages/fr/2020"
    values:
      year: 2020
  -
    scope:
      path: "pages/en/2021"
    values:
      year: 2021
  -
    scope:
      path: "pages/en/2023"
    values:
      year: 2023
  -
    scope:
      path: "pages/fr/2021"
    values:
      year: 2021
  -
    scope:
      path: "pages/fr/2023"
    values:
      year: 2023
  -
    scope:
      path: "_talks/2018"
    values:
      year: 2018
  -
    scope:
      path: "_talks/2019"
    values:
      year: 2019
  -
    scope:
      path: "_talks/2020"
    values:
      year: 2020
  -
    scope:
      path: "_talks/2021"
    values:
      year: 2021
  -
    scope:
      path: "_talks/2023"
    values:
      year: 2023
microtypo:
  median: true

include:
  - _headers
  - _redirects

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script
  - "Rakefile"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
